name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codecov/codecov-action@v3
      - name: Install modules
        run: yarn
      - name: Upload coverage reports to Codecov
        run: npx codecov --token=${{ secrets.CODECOV_TOKEN }} --file=coverage.json
      - name: Run tests
        run: yarn test
